spring:
  datasource:
    url: jdbc:mysql://localhost/hap_demo_service_todo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: hapdemo
    password: handhand
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8000/eureka
swagger:
  oauthUrl: http://localhost:8080/oauth/oauth/authorize
##log
logging:
  level:
    root: error
    com.hand.todo.mapper: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread][%level] %logger- %msg%n"